In [1]:
import numpy as np

In [2]:
pair = {
    'A': 'U',
    'U': 'A',
    'C': 'G',
    'G': 'C'
}

In [26]:
def align(seq, short_seq=5):
    n = len(seq)
    s = np.zeros((n, n), dtype=int)
    p = np.zeros_like(s, dtype=int)
    
    for t in range(short_seq, n):
        for i in range(n - t):
            j = i + t
            s[i, j] = s[i + 1, j]
            if s[i, j - 1] > s[i, j]:
                s[i, j] = s[i, j - 1]
                p[i, j] = -1
            if seq[i] == pair[seq[j]] and s[i + 1, j - 1] + 1 > s[i, j]:
                s[i, j] = s[i + 1, j - 1] + 1
                p[i, j] = -2
            for k in range(i + 1, j):
                if s[i, k] + s[k + 1, j] > s[i, j]:
                    s[i, j] = s[i, k] + s[k + 1, j]
                    p[i, j] = k
                    
#     print(s)
#     print()
#     print(p)

    q = [(0, n-1)]
    t = 0
    
    answer = []
    
    while t <= len(q):
        i, j = q[t]
        
        if i >= n or j >= n:
            break
        
#         print(i, j)
        
        t += 1
        
        if p[i, j] == 0:
            q.append((i + 1, j))
        elif p[i, j] == -1:
            q.append((i, j - 1))
        elif p[i, j] == -2:
            q.append((i + 1, j - 1))
            answer.append([i, j])
        else:
            q.append((i, p[i, j]))
            q.append((p[i, j] + 1, j))
            
    answer = np.array(answer)
    ind = np.argsort(answer[:, 0])
    
    return answer[ind] + 1

In [27]:
align('ACU', 2)

array([[1, 3]])

In [28]:
align('ACCAAGGGUUGGAAC', 2)

array([[ 2,  7],
       [ 3,  6],
       [ 8, 15],
       [ 9, 14],
       [10, 13]])

In [29]:
align('AAACAUGAGGAUUACCCAUGU', 5)

array([[ 3, 21],
       [ 4, 20],
       [ 5, 19],
       [ 6, 18],
       [ 7, 17],
       [ 9, 16],
       [10, 15]])